sudo: required
language: generic 
services:
  - docker
before_install:
  - docker build -t yougalbisht/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true yougalbisht/docker-react npm run test -- --coverage