FROM node:alpine as ProdImageBuilder

WORKDIR /usr/local/frontend

COPY ./package.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx

COPY --from=ProdImageBuilder /usr/local/frontend/build /usr/share/nginx/html
